### ISSUE TITLE
publish release v1.1.0 on NPM

### ISSUE THREAD

**Issue by qdouble** [enten/udk#10]
Hello, I'm looking to use the latest release, but only 1.1.0-rc.0 is on npm

**Comment by enten** [comment]
@qdouble  
I

**Comment by enten** [comment]
@qdouble 
Sorry for delay (it was stucked on my packages registry): `udk v1.1.0` is now availabled on [npm](https://github.com/enten/udk).

**Can you try to install the new version of tell if every works as you expected?**

Just for information: what is your usage of udk? [Angular Universal](https://github.com/enten/angular-universal)? I used udk v1.1.0 to refactor the angular universal starter kit to provide a better developper experience.

**Comment by qdouble** [comment]
@enten hey, Thanks for the update. I'm using it for Angular Universal. 

When I try to add it to my existing project that I had the previous version running in (based on the Universal Starter repo that was using it)... I get:
```
ERROR in No NgModule metadata found for 'AppBrowserModule'.

Name: server
Date: 2019-06-16T19:58:56.084Z
Hash: 6cd5881e1c98c04ac616
Time: 14ms

ERROR in [udk] MultiCompiler
Compilation cancelled due to errors in previous compilers: browser
```

Any idea what I would need to change?

**Comment by enten** [comment]
Did you update your dependencies to angular 8?

Can you share a repo which reproduce your issue?

**Comment by qdouble** [comment]
It even does it with the sample app in your repo. When you build the
browser or server by itself it works fine...the issue comes up with multi
compilation.

**Comment by enten** [comment]
> When you build the browser or server by itself

Can you share commands?

**Comment by qdouble** [comment]
If you go to the examples/angular folder and run `npm run build` you will
get

```
ERROR in No NgModule metadata found for 'AppBrowserModule'.

Name: browser-es6
Date: 2019-06-17T16:47:37.235Z
Hash: 6ef1b92a716987ec1b42
Time: 2ms

ERROR in [udk] MultiCompiler
Compilation cancelled due to errors in previous compilers: browser-es5

Name: server
Date: 2019-06-17T16:47:37.236Z
Hash: 320b72189e7d6e612743
Time: 1ms

ERROR in [udk] MultiCompiler
Compilation cancelled due to errors in previous compilers: browser-es5,
browser-es6
```

However, if you do ng run app:browser or ng run app:server it will compile
those individually. This is hurting me right now since I can't do dev builds.

**Comment by enten** [comment]
@qdouble

I publish udk v1.1.1 to fix some things with the angular devkit.

Can you try to clone and run this repository: https://github.com/enten/angular-universal

Angular example in udk repository isn't up to date.

**Comment by qdouble** [comment]
@enten Hey yeah, it's running great now. Thanks!
