### ISSUE TITLE
Node 10/11 Support

### ISSUE THREAD

**Issue by arunmmanoharan** [enten/udk#7]
Hi, do you have an idea of supporting Node 10/11? Package fails to install on Node 10 since you have engines defined in package.json

**Comment by enten** [comment]
@a2441918 

I [updated node engine version to `>=8.0.0`](https://github.com/enten/udk/commit/42c88a40973118f250c258cab131b5ef91182689) since `udk@1.0.0-alpha.3`.

Is your issue fixed?

**Comment by logesh45** [comment]
I had this issue and it is fixed now. But is still have High cpu usage when udk-ctnr is compiling. more than 175%.

**Comment by enten** [comment]
@logesh45 

Thanks for your feedback.

The udk-ctnr process is just a wrapper process (which restarted when a metafile is updated).

The CPU usage depends to the webpack config used. For example, if you use an angular dynamic webpack config (through angular-cli and udk-builder): the process usage it's often huge (even without udk).

Can we close this issue?

**Comment by logesh45** [comment]
I guess yes. I have tested in node 11 and 10 and it works.
