### ISSUE TITLE
you should probably deprecate webpack-command support

### ISSUE THREAD

**Issue by amitport** [enten/udk#9]
(webpack-command is officially deprecated)

**Comment by enten** [comment]
@amitport 

Thanks.

I added mention below in [FAQ](https://github.com/enten/udk/blob/master/docs/faq.md#can-i-use-webpack-command-instead-of-webpack-cli).

> ### Can I use webpack-command instead of webpack-cli?
> Yes you can.
>
> udk support webpack-cli and webpack-command.
>
> Please note that webpack-command is deprecated since september 2018.
